
import React, {useState, useEffect} from 'react';
import QRCode from 'qrcode.react'
import Select from 'react-select'

const QrCode = ({data}) => {
  const baseSiteUrl = 'https://attandence-bucket.s3.us-east-2.amazonaws.com/siteQR/'
 const [sites, setSites] = useState()
 const [selectedSite, setSelectedSite] = useState()   

    useEffect(() => {
        fetch("https://fn8tsd4pbh.execute-api.us-east-2.amazonaws.com/dev/getManageSitesForWebApp")
        .then(response => response.json())
            // 4. Setting *dogImage* to the image url that we received from the response above
        .then(data => setSites(data))
      },[])

 
      const sitesRecord = sites && sites.data && sites.data.map(s => ({
        "value" : s.SitesName,
        "label" : s.SitesName
      }))
      
      

  return (
    <div>
   
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
  

      
    <main>
      <h1>
       Site QR Downloader
      </h1>
      {/* <select required
        value={selectedSite}
        onChange={e => setSelectedSite(e.target.value)}>
          <option value="">-Select Site-</option>
        {sites&& sites.data && sites.data.map(o => (
          <option key={o._id} value={o.SitesName}>{o.SitesName}</option>
        ))}
      </select> */}

      <Select
        // defaultValue={selectedOption}
        onChange={e => setSelectedSite(e.value)}
        options={sitesRecord}
        // ref={salesPersonRef}
        // value={selectedOption}
        placeholder="Type to Search..."
        required
      />


{selectedSite &&
<div>
<h3>Site Name: {selectedSite} </h3>
<QRCode value={selectedSite} size="250" id="qr-gen" />
<br/>
<button
                onClick={(e) => {
                  e.preventDefault()
                  window.open(
                    baseSiteUrl + (selectedSite && selectedSite.replaceAll(' ', '')) + '.pdf',
                    '_blank',
                  )
                }}
              >
                Download
              </button>
</div>
}
     

 
    </main>

 
  </div>

  );
};

export default QrCode




